# This workflow will build a package using Gradle
# For more information see: https://github.com/actions/setup-java

name: Gradle Build and Test

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Download Gradle
        uses: gradle/gradle-build-action@v2.0.1
        with:
          gradle-version: 4.3
          arguments: wrapper --gradle-version 4.3 --distribution-type all

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.0.1
        with:
          arguments: build
          gradle-home-cache-includes: |
            caches
            notifications
            jdks

      - name: Test with Gradle
        uses: gradle/gradle-build-action@v2.0.1
        with:
          arguments: test