# This workflow will build a package using Maven
# For more information see: https://github.com/actions/setup-java

name: Maven Build and Test

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Build with Maven
        run: ls -la && mvn package -Dmaven.test.skip=true --fail-at-end

      - name: Test with Maven
        run: mvn test -e -X